import { ChessSquareProps } from '../react/components/chess-board/chess-square';

const ChessSquareDetails: ChessSquareProps[] = [
	{ file: 'a', rank: '1', color: 'black' },
	{ file: 'b', rank: '1', color: 'white' },
	{ file: 'c', rank: '1', color: 'black' },
	{ file: 'd', rank: '1', color: 'white' },
	{ file: 'e', rank: '1', color: 'black' },
	{ file: 'f', rank: '1', color: 'white' },
	{ file: 'g', rank: '1', color: 'black' },
	{ file: 'h', rank: '1', color: 'white' },

	{ file: 'a', rank: '2', color: 'white' },
	{ file: 'b', rank: '2', color: 'black' },
	{ file: 'c', rank: '2', color: 'white' },
	{ file: 'd', rank: '2', color: 'black' },
	{ file: 'e', rank: '2', color: 'white' },
	{ file: 'f', rank: '2', color: 'black' },
	{ file: 'g', rank: '2', color: 'white' },
	{ file: 'h', rank: '2', color: 'black' },

	{ file: 'a', rank: '3', color: 'black' },
	{ file: 'b', rank: '3', color: 'white' },
	{ file: 'c', rank: '3', color: 'black' },
	{ file: 'd', rank: '3', color: 'white' },
	{ file: 'e', rank: '3', color: 'black' },
	{ file: 'f', rank: '3', color: 'white' },
	{ file: 'g', rank: '3', color: 'black' },
	{ file: 'h', rank: '3', color: 'white' },

	{ file: 'a', rank: '4', color: 'white' },
	{ file: 'b', rank: '4', color: 'black' },
	{ file: 'c', rank: '4', color: 'white' },
	{ file: 'd', rank: '4', color: 'black' },
	{ file: 'e', rank: '4', color: 'white' },
	{ file: 'f', rank: '4', color: 'black' },
	{ file: 'g', rank: '4', color: 'white' },
	{ file: 'h', rank: '4', color: 'black' },

	{ file: 'a', rank: '5', color: 'black' },
	{ file: 'b', rank: '5', color: 'white' },
	{ file: 'c', rank: '5', color: 'black' },
	{ file: 'd', rank: '5', color: 'white' },
	{ file: 'e', rank: '5', color: 'black' },
	{ file: 'f', rank: '5', color: 'white' },
	{ file: 'g', rank: '5', color: 'black' },
	{ file: 'h', rank: '5', color: 'white' },

	{ file: 'a', rank: '6', color: 'white' },
	{ file: 'b', rank: '6', color: 'black' },
	{ file: 'c', rank: '6', color: 'white' },
	{ file: 'd', rank: '6', color: 'black' },
	{ file: 'e', rank: '6', color: 'white' },
	{ file: 'f', rank: '6', color: 'black' },
	{ file: 'g', rank: '6', color: 'white' },
	{ file: 'h', rank: '6', color: 'black' },

	{ file: 'a', rank: '7', color: 'black' },
	{ file: 'b', rank: '7', color: 'white' },
	{ file: 'c', rank: '7', color: 'black' },
	{ file: 'd', rank: '7', color: 'white' },
	{ file: 'e', rank: '7', color: 'black' },
	{ file: 'f', rank: '7', color: 'white' },
	{ file: 'g', rank: '7', color: 'black' },
	{ file: 'h', rank: '7', color: 'white' },

	{ file: 'a', rank: '8', color: 'white' },
	{ file: 'b', rank: '8', color: 'black' },
	{ file: 'c', rank: '8', color: 'white' },
	{ file: 'd', rank: '8', color: 'black' },
	{ file: 'e', rank: '8', color: 'white' },
	{ file: 'f', rank: '8', color: 'black' },
	{ file: 'g', rank: '8', color: 'white' },
	{ file: 'h', rank: '8', color: 'black' }
];

export { ChessSquareDetails };
